FROM scratch
ADD ./openwrt-armvirt-64-default-rootfs.tar.gz /
ADD ./network /etc/config/
ADD ./boot-openwrt-gateway.sh /sbin/
RUN mkdir -p /etc/sysconfig && echo 0xDEADBEEF > /etc/config/google_fu_mode && chmod 755 /sbin/boot-openwrt-gateway.sh
#&& cp /etc/passwd /etc/sysconfig && cp /etc/group /etc/sysconfig 
CMD ["/sbin/init"]
ENTRYPOINT ["/sbin/boot-openwrt-gateway.sh"]
VOLUME ["/etc/config","/etc/sysconfig","/etc/dropbear"]

